### ISSUE TITLE
Error named unable to resolve host

### ISSUE THREAD

**Issue by shrutibhutaiya** [priyankark/PhonePi_SampleServer#1]
while running as per the instruction, in the android application, getting an alert named "Unable to resolve host 'gyroscope' No address associated with hostname". In this gyroscope.txt file is making in the laptop folder but no values are getting stored.

**Comment by priyankark** [comment]
Is your phone and PC on the same network? Are you entering the ip address: 5000 in the designated text box? Is your IP address correct?

**Comment by shrutibhutaiya** [comment]
Basically i am using Ubuntu and i am creating a hotspot from Ubuntu and connecting it on phone. All other things are perfect. Is it the correct way ?

**Comment by priyankark** [comment]
Have you entered the ip address of your PC in the designated textbox before trying to stream?

**Comment by shrutibhutaiya** [comment]
hey, it worked. Thanks for taking out your time. Problem was with my laptop wifi drivers. It is working fine with another laptop.

**Comment by priyankark** [comment]
I am glad it worked! Closing this issue!
