### ISSUE TITLE
Can't get data stream when executing python PhonePi.py

### ISSUE THREAD

**Issue by karry3775** [priyankark/PhonePi_SampleServer#3]
Initially the app was working fine but when I tried it for the second time, its not displaying data on the command line. I am pretty sure it is some settings issue that I need to handle. Any help is appreciated

**Comment by priyankark** [comment]
Hi, are you entering the right ip address in the app?

**Comment by karry3775** [comment]
Hey thanks for the prompt reply. I got it working, after rebooting my
computer

Thanks
Kartik Prakash

**Comment by priyankark** [comment]
Awesome! Closing this issue then. Thanks for trying the app out.

**Comment by karry3775** [comment]
Thanks , great job on the app btw

**Comment by priyankark** [comment]
Thank you! If you find some time, do leave it a review on the play store.
