### ISSUE TITLE
Can't redeem promo code

### ISSUE THREAD

**Issue by chepo92** [priyankark/PhonePi_SampleServer#8]
Great app, I wanted to use plus version but redeem codes say that are expired, is there any chance to refresh them?  Thanks in advance!

**Comment by priyankark** [comment]
Sure, I could. It just expired. It would be great if you could buy a paid version of the app though as it would help support some of the new features being worked upon.

**Comment by chepo92** [comment]
Thanks @priyankark , I was searching for some apps to steream phone data and saw you I was about to test the free version first.

Is there any plan to support sending data over bluetooth?

**Comment by priyankark** [comment]
Hi chepo, I have added 25 new promo codes.
We are still in the design phase for a newer version of the app and have a lot of cool features planned. I have been reaching out to users to collect feedback on what features they would like to see. Bluetooth sounds cool. If you have any other ideas you want to see in the app, please feel free to write to me at priyankar.kumar98@gmail.com

**Comment by chepo92** [comment]
Sure! 
I tryed to redeem the new codes again in play store  (playstore > menu > redeem ), I get "code didn't work" error

**Comment by priyankark** [comment]
Oh I am sorry! The codes get activated from 3rd July!

**Comment by priyankark** [comment]
Closing..let me know in case you have any questions
